0.1  - First version (#74)
* init (#13)

* installed bulma & router & basic component

* installed font awesome for icons and finished first version of Login

* Adding dependencies

* Refactor to materialize

* login handler improvement

* fix Login in App

* added husky and eslint as devDependencies

* changed config enviroment to browser and ignore jsx format

* added .ignore eslint file to ignore not necessary files by now

* added husky pre-commit hook

* made 'App.js' stateless and fixed husky scripts

* added quiet option to eslint to ignore warnings

* Redux setup (#22)

* Added redux stuff

* comments

* Saga setup

* Login testing + App component test fix

* added basic circle.ci config

* added working_dir name

* added literal paths

* tweaked paths to get rid of redundancy

* removed 'general' line

* fix App test (#30)

* added badge (#25)

* Added app.js

* Created sagas, reducers and actions

* throw new TypeError(' only accepts a callback')

* added babel-node and configured scripts

* removed npx from devDep

* added xo and husky

* Sagas setup on component

* Fix sagas

* Fix tests

* Login.js renamed to index.js

* Feature/login frontend (#33)

* installed bulma & router & basic component

* installed font awesome for icons and finished first version of Login

* Refactor to materialize

* login handler improvement

* fix Login in App

* Login testing + App component test fix

* Created sagas, reducers and actions

* Sagas setup on component

* Fix sagas

* Fix tests

* Login.js renamed to index.js

* init

* fixed eslint problems

* added dependencies for router setup

* Error

* removed react-router-redux from dependencies

* refactored configStore and added router

* Added signup reducer & others. Added prop-types

* Added prop-types to login and fixed prop type error on sagas

* Removed components from App

* removed history from dependencies

* Fix & implement component's test

* sagas testing (login)

* Login sagas testing

* Signup sagas testing

* fix pre-merge

* Remove lock

* added basic structure of navbar

* added basic css

* actions tests

* reducers tests

* Refact errors from single object to array of objects

* fix lock file + syncing branch

* directory/file structure + clean up app.js

* fix prepush script

* mw implemetation

* testing

* testing

* Added route and fix middleware

* comments

* Stardard-ize middleware return format

* added basic navbar structure

* added anchor tag to list itens

* Feature/search soundcloud (#45)

* Added soundcloud mw

* Parallel search middleware

* Reformat search output

* Fix tests import

* changed a tags to Link and changed eslint rule for Link

* added pages components

* fixed profile component and added 'Switch' component

* Feature/search frontend (#49)

* init

* Implemented show results and others...

* Added debounced search

* tests

* input adornment, item buttons & others

* Style & others

* init

* init

* Adding passport local strategy

* added basic tests for dummy components

* changed home to render Landing component

* added middleware to fetch deezer tracks

* linted file

* replaced 'Link' with 'NavLink'

* added music component and removed unused logo

* Added action reducers and others

* adde player functionality

* Added duration to player

* Testing passport

* Added functionality & css

* Improved functionality

* Player/search integration

* Add comparePassword to User Model

* tests

* actions tests

* reducers test

* Deleted empty file

* currentPlaylist + fixes

* Playlist show toggle and stuff

* User.getUserByUserName is not a function

* Fix passport

* Added user obj response

* FIX login & signup

* FIX removed debug lines

* Google oauth & integration

* Signup and auth integration

* fix tests

* adding playlist property to user

* adding song model

* adding playlist model

* fixing user.js

* fixing conflicts

* add playlist to User

* fixing merge

* Fix user

* init

* profile's actions, reducers, sagas

* fix subdocuments

* Moar stufff

* fix propTypes

* Added .env files description on readme

* Change pw frontend

* change pic stuff

* Improved change pic

* Finished style stuff

* Finished style stuff

* Change pic actions, reducer, saga

* fix tests

* basic routes

* Cleaned up e2e

* Fix tests

* Landing page

* Landing page

* clean spaces

* Conflict error

* Fixed error from CircleCI

* simple routes setup

* Adding changes

* Update Package.json

I removed the connnect-flash dependency

* merge development branch

* routes first version

* routes clean up

* Styles and stuff

* FIX authenticated search bug

* Style spreding

* Finished implementing styled-components

* Finished implementing styled-components

* added list component to render playlists

* added basic dnd configuration

* Setup nested DnD lists + actions + reducers

* reducer + saga

* fix routes v1

* Fix setPlaylists route

* Fix playlists retrieval (backend) + checkboxes

* Fix tests & added fix for drag+update

* added loading 'icon'

* added play button

* Added add and delete playlists functionality

* config for Dailymotion API

* adding _dailymotion to parallelSearch

* Added play playlist functionality

* Dailymotion API error fixed

* Dailymotion API error fixed

* started to create add song to playlist functionality

* fix typo

* started implementing reducer for add song to playlists functionallity

* added add track functionality

* added playlists menu on add click

* fixed playlist proptype

* Fix player play button

* Fix playlist menu crash on close, removed dummy playlists, fix tests

* Changed redirect to /music instead of /

* Fix bug when adding songs, got response 400 always

* improved playlist menu style and functionality

* Player's showPlaylist disabled if there isn't a playlist

* improved playlists and songs diplay, were too wide and tall

* Changed playlist buttons disposition

* fixed playlist proptype

* wrote reducer to remove song from playlist

* Added add song to playlist functionality

* Added playlist rename. Unfinished (bug)

* Added post-heroku script

* Testing without post deploy

* post deploy script

* deploy script

* Re-structure folders

* test express serve index.html file

* Removed babel from start script

* README

* Feature/playlist management (#70)

* added list component to render playlists

* added basic dnd configuration

* Setup nested DnD lists + actions + reducers

* reducer + saga

* fix routes v1

* Fix setPlaylists route

* Fix playlists retrieval (backend) + checkboxes

* Fix tests & added fix for drag+update

* added loading 'icon'

* added play button

* Added add and delete playlists functionality

* Added play playlist functionality

* started to create add song to playlist functionality

* started implementing reducer for add song to playlists functionallity

* added add track functionality

* added playlists menu on add click

* fixed playlist proptype

* Fix player play button

* Fix playlist menu crash on close, removed dummy playlists, fix tests

* Changed redirect to /music instead of /

* Fix bug when adding songs, got response 400 always

* improved playlist menu style and functionality

* Player's showPlaylist disabled if there isn't a playlist

* improved playlists and songs diplay, were too wide and tall

* Changed playlist buttons disposition

* fixed playlist proptype

* wrote reducer to remove song from playlist

* Added add song to playlist functionality

* Added playlist rename. Unfinished (bug)

* FIX playlist rename bug

* Disabled deezer support until bug is fixed

* Changed main prop in package.json